name: Go Linting

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      golangci-version:
        required: true
        type: string
jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ inputs.golangci-version }}
  tidy:
    name: Go mod tidy check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Check if go.mod is tidy
        run: |
          go mod tidy -diff
          if [ -n "$(go mod tidy -diff)" ]; then
            echo "::error::go.mod or go.sum files are not tidy"
            echo "Please run 'go mod tidy' and commit the changes"
            exit 1
          fi
